apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "{{ .Values.service.loadBalancerInternal }}"
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: {{ .Values.deployment.name }}
  type:  {{ .Values.service.type }}
status:
  loadBalancer: {}